"""
PlatformIO pre-build script: generates include/generated_config.h with
  • XG_CA_CERT — the broker root CA from certs/ca.pem (empty string if absent)
  • XG_FALLBACK_BROKER_HOST/PORT — from secrets.ini (empty if unset)
Nothing secret is compiled in: device credentials arrive over Bluetooth at setup time.
"""
import os

Import("env")  # noqa: F821  (provided by PlatformIO)

project_dir = env["PROJECT_DIR"]  # noqa: F821
ca_path = os.path.join(project_dir, "certs", "ca.pem")
out_path = os.path.join(project_dir, "include", "generated_config.h")


def c_string(text: str) -> str:
    lines = text.replace("\r\n", "\n").split("\n")
    return "\n".join('  "' + line.replace("\\", "\\\\").replace('"', '\\"') + '\\n"' for line in lines if line) or '  ""'


ca = open(ca_path, encoding="utf-8").read() if os.path.exists(ca_path) else ""
host = env.GetProjectOption("custom_fallback_broker_host", "")  # noqa: F821
port = env.GetProjectOption("custom_fallback_broker_port", "1883")  # noqa: F821

content = f"""// AUTO-GENERATED by scripts/embed_config.py — do not edit, do not commit.
#pragma once
#define XG_HAS_CA_CERT {1 if ca else 0}
static const char XG_CA_CERT[] =
{c_string(ca)};
#define XG_FALLBACK_BROKER_HOST "{host}"
#define XG_FALLBACK_BROKER_PORT {int(port or 1883)}
"""

previous = open(out_path, encoding="utf-8").read() if os.path.exists(out_path) else None
if previous != content:
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
print("[xg] generated_config.h: CA cert %s, fallback broker %s" % ("embedded" if ca else "not set", host or "none"))
