/**
 * Plant conditions the app knows how to explain. Any model's label is matched to one of these
 * (see labels.ts); a label that matches nothing still gets advice for its category.
 * Covers the 38 PlantVillage classes plus common garden problems other models report.
 */
import type { ScanCategory, ScanSeverity } from '@xeno/shared';

export interface ConditionInfo {
  id: string;
  name: string;
  category: ScanCategory;
  severity: ScanSeverity;
  /** Each inner list is a set of words that must all appear in the normalised label. */
  match: string[][];
  summary: string;
  treatment: string[];
  prevention: string[];
}

const FUNGAL_PREVENTION = [
  'Water the soil, not the leaves, ideally in the morning so plants dry quickly.',
  'Give plants space and prune crowded growth so air can move between leaves.',
  'Clear fallen and dead leaves; they carry spores into the next season.',
];

export const CONDITIONS: ConditionInfo[] = [
  {
    id: 'healthy',
    name: 'Healthy',
    category: 'healthy',
    severity: 'none',
    match: [['healthy']],
    summary: 'No signs of disease on this leaf.',
    treatment: [],
    prevention: [
      'Keep watering steady: Xeno Auto mode holds the soil in the right range.',
      'Check the underside of leaves every week; problems are easiest to stop early.',
    ],
  },
  {
    id: 'early_blight',
    name: 'Early blight',
    category: 'fungal',
    severity: 'medium',
    match: [['early', 'blight'], ['alternaria']],
    summary: 'A fungal disease (Alternaria) that makes brown spots with rings like a target, usually on older, lower leaves first.',
    treatment: [
      'Remove the spotted leaves and throw them away, not on the compost.',
      'Spray a copper- or chlorothalonil-based fungicide every 7–10 days while it spreads.',
      'Mulch the soil so rain or watering doesn’t splash spores onto the leaves.',
    ],
    prevention: [...FUNGAL_PREVENTION, 'Rotate crops: don’t grow tomato or potato in the same spot every year.'],
  },
  {
    id: 'late_blight',
    name: 'Late blight',
    category: 'fungal',
    severity: 'high',
    match: [['late', 'blight'], ['phytophthora']],
    summary: 'A fast-spreading water mould (Phytophthora) that causes dark, greasy patches and can kill a plant within days in cool, wet weather.',
    treatment: [
      'Act today: remove and bag every affected leaf and stem.',
      'Spray a fungicide made for late blight (copper or mancozeb) on the rest of the plant.',
      'If most of the plant is affected, pull it out so it can’t infect neighbours.',
    ],
    prevention: [...FUNGAL_PREVENTION, 'Choose blight-resistant varieties next season.'],
  },
  {
    id: 'bacterial_spot',
    name: 'Bacterial spot',
    category: 'bacterial',
    severity: 'medium',
    match: [['bacterial', 'spot'], ['xanthomonas']],
    summary: 'Bacteria (Xanthomonas) that make small, dark, water-soaked spots on leaves and fruit.',
    treatment: [
      'Remove badly spotted leaves.',
      'Spray a copper-based bactericide; it slows the spread but can’t cure infected leaves.',
      'Don’t touch or prune the plants while they are wet: that spreads bacteria.',
    ],
    prevention: [...FUNGAL_PREVENTION, 'Use certified disease-free seeds and transplants.'],
  },
  {
    id: 'septoria_leaf_spot',
    name: 'Septoria leaf spot',
    category: 'fungal',
    severity: 'medium',
    match: [['septoria']],
    summary: 'A fungus that covers lower leaves with many small round spots that have grey centres and dark edges.',
    treatment: [
      'Pick off spotted lower leaves.',
      'Apply a copper or chlorothalonil fungicide every 7–10 days.',
      'Mulch around the stem to stop soil splashing up.',
    ],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'leaf_mold',
    name: 'Leaf mould',
    category: 'fungal',
    severity: 'medium',
    match: [['leaf', 'mold'], ['leaf', 'mould'], ['fulvia'], ['cladosporium']],
    summary: 'A fungus that loves humid air: pale yellow patches on top of the leaf, olive-green mould underneath.',
    treatment: [
      'Remove the affected leaves.',
      'Lower the humidity: ventilate, and space the plants out.',
      'Use a fungicide labelled for leaf mould if it keeps spreading.',
    ],
    prevention: [...FUNGAL_PREVENTION, 'In a greenhouse, keep humidity under about 85 %.'],
  },
  {
    id: 'target_spot',
    name: 'Target spot',
    category: 'fungal',
    severity: 'medium',
    match: [['target', 'spot'], ['corynespora']],
    summary: 'A fungus (Corynespora) that makes brown spots with light rings on leaves, stems and fruit.',
    treatment: [
      'Remove the infected leaves.',
      'Spray a broad-spectrum fungicide such as chlorothalonil.',
      'Improve airflow around the plant.',
    ],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'spider_mites',
    name: 'Spider mites',
    category: 'pest',
    severity: 'medium',
    match: [['spider', 'mite'], ['spider', 'mites'], ['two', 'spotted'], ['mite']],
    summary: 'Tiny mites that suck sap, leaving fine yellow speckles and sometimes thin webbing under leaves.',
    treatment: [
      'Spray the undersides of the leaves with a strong jet of water to knock them off.',
      'Use insecticidal soap or neem oil every 5–7 days, three times.',
      'Remove heavily webbed leaves.',
    ],
    prevention: ['Mites thrive in hot, dry air: keep plants well watered.', 'Check leaf undersides weekly in hot weather.'],
  },
  {
    id: 'yellow_leaf_curl_virus',
    name: 'Yellow leaf curl virus',
    category: 'viral',
    severity: 'high',
    match: [['yellow', 'leaf', 'curl'], ['tylcv']],
    summary: 'A virus spread by whiteflies: leaves turn yellow, curl upward and the plant stops growing.',
    treatment: [
      'There is no cure: remove and bag infected plants to protect the others.',
      'Control whiteflies with yellow sticky traps, neem oil or insecticidal soap.',
    ],
    prevention: ['Cover young plants with insect netting.', 'Grow resistant varieties.', 'Keep weeds down; they host whiteflies.'],
  },
  {
    id: 'mosaic_virus',
    name: 'Mosaic virus',
    category: 'viral',
    severity: 'high',
    match: [['mosaic']],
    summary: 'A virus that makes a mottled light- and dark-green pattern and distorted leaves.',
    treatment: [
      'There is no cure: remove infected plants.',
      'Wash your hands and disinfect tools after touching them; the virus spreads by contact.',
    ],
    prevention: ['Don’t smoke near plants (tobacco can carry the virus).', 'Use resistant varieties and clean seed.', 'Control aphids, which spread some mosaic viruses.'],
  },
  {
    id: 'apple_scab',
    name: 'Apple scab',
    category: 'fungal',
    severity: 'medium',
    match: [['scab']],
    summary: 'A fungus that makes olive-brown, velvety spots on leaves and corky patches on fruit.',
    treatment: [
      'Remove and destroy infected leaves and fruit.',
      'Spray a fungicide (captan, sulphur or myclobutanil) from bud break in wet springs.',
    ],
    prevention: ['Rake up and remove fallen leaves in autumn.', 'Prune to open the tree’s centre to sun and air.', 'Plant scab-resistant varieties.'],
  },
  {
    id: 'black_rot',
    name: 'Black rot',
    category: 'fungal',
    severity: 'medium',
    match: [['black', 'rot']],
    summary: 'A fungus that causes brown leaf spots with purple edges and rotting, shrivelled fruit.',
    treatment: [
      'Cut out infected leaves, fruit and dead wood.',
      'Apply a fungicide (captan or mancozeb) during wet weather.',
    ],
    prevention: ['Remove mummified fruit from the plant and the ground.', ...FUNGAL_PREVENTION.slice(0, 2)],
  },
  {
    id: 'cedar_apple_rust',
    name: 'Cedar apple rust',
    category: 'fungal',
    severity: 'low',
    match: [['cedar'], ['gymnosporangium']],
    summary: 'A rust fungus that needs both apple and juniper/cedar trees: bright orange-yellow spots on leaves.',
    treatment: ['Remove badly spotted leaves.', 'Apply a fungicide (myclobutanil or sulphur) in spring if it is a yearly problem.'],
    prevention: ['Remove nearby juniper or cedar galls where possible.', 'Choose rust-resistant apple varieties.'],
  },
  {
    id: 'powdery_mildew',
    name: 'Powdery mildew',
    category: 'fungal',
    severity: 'low',
    match: [['powdery', 'mildew'], ['powdery']],
    summary: 'A fungus that looks like white flour dusted on the leaves. It weakens the plant but rarely kills it.',
    treatment: [
      'Remove the worst leaves.',
      'Spray diluted milk (1 part milk : 9 parts water), potassium bicarbonate or sulphur every week.',
    ],
    prevention: ['Plant in full sun with good airflow.', 'Avoid too much nitrogen fertiliser; soft new growth is easily infected.'],
  },
  {
    id: 'downy_mildew',
    name: 'Downy mildew',
    category: 'fungal',
    severity: 'medium',
    match: [['downy', 'mildew'], ['downy']],
    summary: 'A water mould: yellow patches on top of the leaf, grey-purple fuzz underneath, worst in cool, wet weather.',
    treatment: ['Remove infected leaves.', 'Apply a copper-based fungicide.', 'Water early so leaves dry by evening.'],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'gray_leaf_spot',
    name: 'Grey leaf spot',
    category: 'fungal',
    severity: 'medium',
    match: [['cercospora'], ['gray', 'leaf', 'spot'], ['grey', 'leaf', 'spot']],
    summary: 'A fungus (Cercospora) that makes long, rectangular grey-tan spots between the leaf veins.',
    treatment: ['Remove heavily affected leaves.', 'Apply a fungicide (strobilurin or triazole) if it reaches the upper leaves.'],
    prevention: ['Rotate crops and till in old crop debris.', 'Grow resistant hybrids.'],
  },
  {
    id: 'common_rust',
    name: 'Rust',
    category: 'fungal',
    severity: 'medium',
    match: [['common', 'rust'], ['rust']],
    summary: 'A fungus that makes small, powdery orange-brown bumps (pustules) on the leaves.',
    treatment: ['Remove infected leaves.', 'Apply a fungicide (sulphur, myclobutanil or a triazole) when pustules first appear.'],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'northern_leaf_blight',
    name: 'Northern leaf blight',
    category: 'fungal',
    severity: 'medium',
    match: [['northern', 'leaf', 'blight'], ['northern', 'blight'], ['exserohilum']],
    summary: 'A fungus that makes long, cigar-shaped grey-green lesions on corn leaves.',
    treatment: ['Apply a fungicide if lesions reach the leaves above the cob before tasselling.'],
    prevention: ['Rotate crops and bury old corn debris.', 'Grow resistant hybrids.'],
  },
  {
    id: 'esca',
    name: 'Esca (black measles)',
    category: 'fungal',
    severity: 'high',
    match: [['esca'], ['black', 'measles']],
    summary: 'A wood disease of grapevines: tiger-striped leaves and spotted berries; the vine can die suddenly.',
    treatment: ['Cut out dead or infected wood well below the damage and seal large cuts.', 'Remove vines that collapse.'],
    prevention: ['Prune in dry weather and protect pruning wounds.', 'Disinfect pruning tools between vines.'],
  },
  {
    id: 'grape_leaf_blight',
    name: 'Leaf blight (Isariopsis)',
    category: 'fungal',
    severity: 'medium',
    match: [['isariopsis'], ['leaf', 'blight']],
    summary: 'A fungus that makes dark, angular spots that join into large dead patches on the leaves.',
    treatment: ['Remove infected leaves.', 'Spray a copper or mancozeb fungicide.'],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'citrus_greening',
    name: 'Citrus greening (HLB)',
    category: 'bacterial',
    severity: 'high',
    match: [['greening'], ['huanglongbing'], ['haunglongbing'], ['hlb']],
    summary: 'A bacterial disease spread by psyllid insects: blotchy yellow leaves and small, bitter, lopsided fruit.',
    treatment: ['There is no cure: remove infected trees to protect healthy ones.', 'Control psyllids on nearby citrus.'],
    prevention: ['Buy certified disease-free trees.', 'Inspect new growth for psyllids regularly.'],
  },
  {
    id: 'leaf_scorch',
    name: 'Leaf scorch',
    category: 'fungal',
    severity: 'low',
    match: [['leaf', 'scorch'], ['scorch']],
    summary: 'A fungus (on strawberry) that makes many small purple spots which merge until the leaf looks burnt.',
    treatment: ['Remove infected leaves.', 'Apply a fungicide labelled for strawberries if it spreads.'],
    prevention: ['Renew strawberry beds every 3–4 years.', ...FUNGAL_PREVENTION.slice(0, 2)],
  },
  {
    id: 'anthracnose',
    name: 'Anthracnose',
    category: 'fungal',
    severity: 'medium',
    match: [['anthracnose'], ['colletotrichum']],
    summary: 'A fungus that makes dark, sunken spots on leaves, stems and fruit, worst in warm, wet weather.',
    treatment: ['Remove infected parts.', 'Spray a copper-based fungicide.'],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'wilt',
    name: 'Wilt disease',
    category: 'fungal',
    severity: 'high',
    match: [['fusarium'], ['verticillium'], ['wilt']],
    summary: 'A soil disease that blocks the plant’s water pipes: leaves yellow and wilt even when the soil is moist.',
    treatment: ['Remove and bag affected plants with their roots.', 'Don’t replant the same crop in that soil for a few years.'],
    prevention: ['Rotate crops.', 'Choose resistant varieties.', 'Avoid overwatering: soggy soil helps soil diseases.'],
  },
  {
    id: 'root_rot',
    name: 'Root rot',
    category: 'fungal',
    severity: 'high',
    match: [['root', 'rot']],
    summary: 'Roots rotting in waterlogged soil: the plant wilts and yellows although the soil is wet.',
    treatment: ['Stop watering until the top of the soil dries.', 'Repot or replant into well-draining soil, trimming brown, mushy roots.'],
    prevention: ['Let the soil dry a little between waterings: lower the Auto target in Xeno.', 'Make sure pots and beds drain.'],
  },
  {
    id: 'leaf_spot',
    name: 'Leaf spot',
    category: 'fungal',
    severity: 'low',
    match: [['leaf', 'spot'], ['spot']],
    summary: 'Spots on the leaves caused by a fungus or bacteria.',
    treatment: ['Remove spotted leaves.', 'Apply a copper-based spray if it keeps spreading.'],
    prevention: FUNGAL_PREVENTION,
  },
  {
    id: 'aphids',
    name: 'Aphids',
    category: 'pest',
    severity: 'low',
    match: [['aphid'], ['aphids']],
    summary: 'Small soft insects in clusters on new growth; they suck sap and leave sticky honeydew.',
    treatment: ['Spray them off with water.', 'Use insecticidal soap or neem oil.'],
    prevention: ['Encourage ladybirds and lacewings.', 'Avoid too much nitrogen fertiliser.'],
  },
  {
    id: 'whitefly',
    name: 'Whiteflies',
    category: 'pest',
    severity: 'medium',
    match: [['whitefly'], ['whiteflies'], ['white', 'fly']],
    summary: 'Tiny white flying insects under the leaves; they weaken plants and spread viruses.',
    treatment: ['Hang yellow sticky traps.', 'Spray neem oil or insecticidal soap under the leaves.'],
    prevention: ['Inspect new plants before bringing them in.', 'Use insect netting on young plants.'],
  },
  {
    id: 'nutrient_deficiency',
    name: 'Nutrient deficiency',
    category: 'nutrient',
    severity: 'low',
    match: [['deficiency'], ['deficient'], ['chlorosis'], ['nitrogen'], ['potassium'], ['magnesium']],
    summary: 'The leaf colour suggests the plant is short of a nutrient.',
    treatment: ['Feed with a balanced fertiliser.', 'Yellow older leaves often mean nitrogen; yellow between veins often means magnesium or iron.'],
    prevention: ['Feed regularly during the growing season.', 'Add compost to the soil.'],
  },
];

/** Advice for a label we can't match, by category. */
export const CATEGORY_FALLBACK: Record<Exclude<ScanCategory, 'healthy'>, Pick<ConditionInfo, 'severity' | 'summary' | 'treatment' | 'prevention'>> = {
  fungal: {
    severity: 'medium',
    summary: 'Looks like a fungal disease.',
    treatment: ['Remove the affected leaves.', 'Apply a broad-spectrum fungicide (copper or chlorothalonil) if it spreads.'],
    prevention: FUNGAL_PREVENTION,
  },
  bacterial: {
    severity: 'medium',
    summary: 'Looks like a bacterial disease.',
    treatment: ['Remove the affected leaves.', 'Spray a copper-based bactericide.', 'Don’t handle the plants while wet.'],
    prevention: FUNGAL_PREVENTION,
  },
  viral: {
    severity: 'high',
    summary: 'Looks like a virus. Viruses can’t be cured.',
    treatment: ['Remove the infected plant to protect the others.', 'Control the insects that spread viruses (aphids, whiteflies).'],
    prevention: ['Use resistant varieties and clean seed.', 'Disinfect tools.'],
  },
  pest: {
    severity: 'medium',
    summary: 'Looks like insect or mite damage.',
    treatment: ['Check the undersides of the leaves for the pest.', 'Use insecticidal soap or neem oil.'],
    prevention: ['Inspect plants weekly.', 'Encourage natural predators.'],
  },
  nutrient: {
    severity: 'low',
    summary: 'Looks like a nutrient problem.',
    treatment: ['Feed with a balanced fertiliser.'],
    prevention: ['Add compost and feed regularly in the growing season.'],
  },
  unknown: {
    severity: 'medium',
    summary: 'The model found a problem with this leaf.',
    treatment: ['Remove the affected leaves and watch the plant over the next days.', 'Scan again in daylight if it gets worse.'],
    prevention: FUNGAL_PREVENTION,
  },
};
